# Generated by Django 2.0.6 on 2018-06-18 18:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='ship_free',
        ),
        migrations.AlterField(
            model_name='goods',
            name='goods_brief',
            field=models.TextField(blank=True, max_length=50, null=True, verbose_name='商品简短描述'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='goods_cut_off_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='商品销售截止时间'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='goods_red_label',
            field=models.TextField(blank=True, max_length=15, null=True, verbose_name='商品标签'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='shop_old_price',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='本店原先价格'),
        ),
        migrations.AlterField(
            model_name='goodscategory',
            name='parent_category',
            field=models.ForeignKey(blank=True, help_text='父目录', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='goods.GoodsCategory', verbose_name='父类目级别'),
        ),
    ]
