# Generated by Django 2.0.6 on 2018-06-18 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20180618_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodscategory',
            name='category_front_image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/images/', verbose_name='封面图'),
        ),
        migrations.AlterField(
            model_name='goodsimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='goods/images/', verbose_name='图片'),
        ),
    ]
